# Generated by Django 3.2.7 on 2021-11-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='app.Service'),
        ),
    ]
