# Generated by Django 3.2.7 on 2021-11-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_barber_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booking_time',
        ),
    ]
